[GLOBAL]
pants_version = "2.23.1"
backend_packages = [
#  "pants.backend.shell",
  "pants.backend.docker",
  "pants.backend.python",
#  "pants.backend.python.lint.black",
  "pants.backend.awslambda.python",
]

[python]
interpreter_constraints = ["==3.10.*"]  # Match AWS Lambda runtime
enable_resolves = true
resolves = { python-default = "requirements.txt" }


#
#[awslambda]
#runtime = "python3.10"

#[tailor]
#ignore_patterns = ["*.venv", "__pycache__"]

#[backend]
## Enable Python and AWS Lambda-specific plugins
#packages = [
#    "pants.backend.python",
#    "pants.backend.awslambda.python",
#]

